#!/bin/bash

# set git color
git config --global color.ui auto

# config git
git config --global core.editor vim

git config --global http.postBuffer 524288000
git config --global https.postBuffer 524288000

git config --global http.sslVerify "false"
git config --global http.version "HTTP/1.1"

git config --global http.lowSpeedLimit 0
git config --global http.lowSpeedTime 999999

git config --global http.maxRequestBuffer 100M
git config --global https.maxRequestBuffer 100M

git config --global core.compression 0

# git cloe xxx --depth 1
# cd xxx
# git fetch --unshadow
